# Generated by Django 4.2.20 on 2025-03-28 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='treatments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tname', models.CharField(max_length=100)),
                ('timage', models.ImageField(upload_to='photos/')),
                ('charge', models.IntegerField()),
            ],
        ),
    ]
