# Generated by Django 4.2.20 on 2025-03-28 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='dentist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('em', models.CharField(max_length=50)),
                ('cno', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('photo', models.ImageField(upload_to='photos/')),
                ('quali', models.CharField(max_length=50)),
                ('uname', models.CharField(max_length=50)),
                ('pword', models.CharField(max_length=50)),
            ],
        ),
    ]
