# Generated by Django 4.2.20 on 2025-03-28 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_dentist'),
    ]

    operations = [
        migrations.AddField(
            model_name='dentist',
            name='rights',
            field=models.CharField(default='ND', max_length=50),
        ),
    ]
