# Generated by Django 4.2.20 on 2025-03-29 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_dentist_rights'),
    ]

    operations = [
        migrations.CreateModel(
            name='userreg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('em', models.CharField(max_length=50)),
                ('cno', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('uname', models.CharField(max_length=50)),
                ('pword', models.CharField(max_length=50)),
                ('rights', models.CharField(default='U', max_length=50)),
            ],
        ),
    ]
