# Generated by Django 4.2.20 on 2025-03-29 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_userreg'),
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bno', models.IntegerField()),
                ('bdate', models.DateField()),
                ('rdate', models.DateField()),
                ('dname', models.CharField(max_length=50)),
                ('fname', models.CharField(max_length=100)),
                ('tname', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='dentist',
            old_name='fname',
            new_name='dname',
        ),
    ]
