# Generated by Django 4.2.20 on 2025-03-29 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_booking_rename_fname_dentist_dname'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(default='New Booking', max_length=50),
        ),
    ]
