# Generated by Django 4.2.20 on 2025-04-01 07:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_booking_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='fname',
        ),
        migrations.AddField(
            model_name='booking',
            name='did',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='patient',
            field=models.CharField(default='x', max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='pid',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='booking',
            name='bdate',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
