# Generated by Django 4.2.20 on 2025-04-01 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_booking_fname_booking_did_booking_patient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='charge',
            field=models.IntegerField(default=0),
        ),
    ]
